favicon: /favicon.ico


# 首页标语
banner:
  enable: true
  title: 大他者并不存在
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

# 公告，显示在所有文章卡片的最上方，标语的下方
notice:
  enable: true
  content: 欢迎光临我的博客

# 背景
bg_image:
  enable: true
  url: /images/background.jpg
  # dark:
  blur: 10px # 设置背景模糊程度
  opacity: 0.6  

# 点击图片，放大预览
medium_zoom: true  

# 头像设置
avatar:
  enable: true
  url: /images/avatar.png
  rounded: true  # 头像是否圆角
  opacity: 1     # 头像透明度
  mickey_mouse: false
  status:
    enable: true
    emoji: 🦜
    message: 象征界

pages:
  #- name: 我的小伙伴们
  #  url: /links/
  #  icon: ri:genderless-line
  #  color: dodgerblue

# 社交图标
social:
  - name: GitHub
    link: https://github.com/FZ688
    icon: ri:github-line
    color: '#181717' 

# 页脚
footer:
  since: 2025 # 起始年份
  # icon:
  #   name: ri:cloud-line
  #   animated: true
  #   color: '#0078E7'
  #   url: 你的链接
  #   title: 自拟
  powered:
    enable: false # 是否显示主题名称
  # beian:
  #   enable: true # 是否显示备案
  #   # ICP备案
  #   icp: 苏ICP备xxxxxxxxxx号
  #   # 公安备案
  #   gongan:
  #     enable: true
  #     text: 苏公网安备XXXXXXXX号
  #     id: XXXXXXXX
 
  live_time: # 运行时间
    enable: true
    prefix: 感谢陪伴
    suffix: (●'◡'●)
    start_time: '2025-09-24T00:00:00' # 开始时间
#下面是自定义文本，你可以自由填写
#custom_text: YourText <a href="yourLink" rel="noopener" target="_blank">Description</a>

# 取消打赏
reward:
  enable: false
  #icon: ri:hand-coin-line
  #comment: 夜梦星尘这么可爱，你真的不考虑考虑嘛？
  #methods:
    # - name: 支付宝
    #   path: https://cdn.yunyoujun.cn/img/donate/alipay-qrcode.jpg
    #   color: '#00A3EE'
    #   icon: ri:alipay-line
    #   link: https://xxxx
    # - name: QQ 支付
    #   path: 你的QQ收款码
    #   color: '#12B7F5'
    #   icon: ri:qq-line
    # - name: 微信支付
    #   path: 你的微信收款码
    #   color: '#2DC100'
    #   icon: ri:wechat-pay-line

# 菜单
menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    - type: categories
      path: /categories/
      icon: ri:folder-2-line
    - type: tags
      path: /tags/
      icon: ri:price-tag-3-line
  custom:
    title: 文档
    path: https://yun.yunyoujun.cn
    icon: ri:settings-line  


say:
  enable: true
  api: /data/sentences.json
  hitokoto:
    enable: false